version: '3'

services: 
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8000:80
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
            APP_ENV: dev
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony
    mysql:
        image: mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_DATABASE: symfony_db
            MYSQL_USER: symfony_user
            MYSQL_PASSWORD: symfony_password
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3307:3306
        volumes: 
            - ./mysql:/var/lib/mysql
        networks:
            - symfony
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.1
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8081:80"
        networks:
            - symfony
    node:
        build:
            context: .
            dockerfile: Dockerfile-node
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/:/var/www/frontend/
            - /frontend/node_modules
        networks:
            - symfony



networks:
    symfony:
